---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE

DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - DOCKERFILE_HADOLINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY

EMAIL_REPORTER: false
FILEIO_REPORTER: false
MARKDOWN_SUMMARY_REPORTER: true
SHOW_ELAPSED_TIME: true